{
 "title": "PODSEMANTICNAME",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"memory_usage_bytes\") FROM \"kubernetes_pod_container\" WHERE (\"pod_name\" =~ /PODNAMEHERE*/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=", "value": "PODNAMEHERE" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"rootfs_used_bytes\") FROM \"kubernetes_pod_container\" WHERE (\"pod_name\" =~ /PODNAMEHERE*/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "rootfs_used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=", "value": "PODNAMEHERE" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"cpu_usage_nanocores\") FROM \"kubernetes_pod_container\" WHERE (\"pod_name\" =~ /PODNAMEHERE*/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=", "value": "PODNAMEHERE" }
     ]
    }
   ]
  }
 ]
}