apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          imagePullPolicy: Never
          image: mysql
          volumeMounts:
            - name: mysql-volume
              mountPath: /app
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: root
            - name: MYSQL_DATABASE_NAME
              value: wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wpsqlpass
                  key: wpsqlpass
            - name: MYSQL_USERNAME
              value: wordpress
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-storage