apiVersion: v1
kind: Service
metadata:
  name: pma
spec:
  type: LoadBalancer
  selector:
    app: pma
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: pma
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
        - name: pma
          imagePullPolicy: Never
          image: pma
          ports:
          - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql
            - name: BLOWFISH_SECRET
              valueFrom:
                secretKeyRef:
                  name: pmablowfish
                  key: blowfish