apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    user:
    password:
    url: http://INFLUXDB_HOST:INFLUXDB_PORT
    isDefault: true
    jsonData:
      httpMode: GET
    editable: false